name: Build Package Tracer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt-get install desktop-file-utils libfuse2
          wget https://github.com/AppImage/pkg2appimage/raw/master/pkg2appimage
          chmod +x pkg2appimage
      # Runs a set of commands using the runners shell
      - name: Build
        run: ./pkg2appimage PacketTracer.yml
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PacketTracer
          path: out/
